"""Create User_bet table

Revision ID: 2c0cdc9673c5
Revises: 65ce00c14724
Create Date: 2023-01-21 19:49:04.913378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0cdc9673c5'
down_revision = '65ce00c14724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_fs_uniquifier', type_='unique')
        batch_op.drop_constraint('fk_user_role_id_role', type_='foreignkey')
        batch_op.drop_column('fs_uniquifier')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('user_bet', schema=None) as batch_op:
        batch_op.alter_column('user_bet',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bet', schema=None) as batch_op:
        batch_op.alter_column('user_bet',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fs_uniquifier', sa.VARCHAR(length=255), nullable=False))
        batch_op.create_foreign_key('fk_user_role_id_role', 'role', ['role_id'], ['id'])
        batch_op.create_unique_constraint('uq_user_fs_uniquifier', ['fs_uniquifier'])

    # ### end Alembic commands ###
