"""User update

Revision ID: 73974f5638c5
Revises: d85d1f02e977
Create Date: 2023-01-23 19:55:03.507980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73974f5638c5'
down_revision = 'd85d1f02e977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###
